version: '3'
services:
  localstack:
    container_name: "localstack_main"
    image: localstack/localstack:latest
    ports:
      - '4566-4599:4566-4599'
      - '${LAMBDA_EXECUTOR_PORT-9001}:${LAMBDA_EXECUTOR_PORT-9001}'
    environment:
      - SERVICES=s3,dynamodb,lambda
      - DEBUG=1
      - DATA_DIR=/localstack/data   # Update DATA_DIR to point to new directory
      - PORT_WEB_UI=8080
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
      - START_WEB=0
    volumes:
      - "./.localstack:/localstack/data"    # map local directory to new directory in Docker container
      - "/var/run/docker.sock:/var/run/docker.sock"
